from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="salim-api-gen",
    version="0.7.0",
    author="Salim Bin Yousuf",
    author_email="salim.bin.yousuf2@gmail.com",
    description="A comprehensive library for generating API wrappers, documentation, and mock servers from OpenAPI/Swagger and RAML specifications",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/SalimBinYousuf1/salim-api-gen",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Software Development :: Code Generators",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    python_requires=">=3.7",
    install_requires=[
        "pyyaml>=5.4,<7.0",
        "requests>=2.25,<3.0",
        "aiohttp>=3.7,<4.0",
        "jinja2>=2.11,<4.0",
        "ratelimit>=2.2,<3.0",
        "jsonschema>=3.2,<5.0",
        "fastapi>=0.68.0,<1.0",
        "uvicorn>=0.15.0,<1.0",
        "markdown2>=2.4.0,<3.0",
        "inquirer>=2.7.0,<3.0",
        "ramlfications>=0.1.9,<0.2.0",
        "click>=7.1.2,<8.0",
        "colorama>=0.4.4,<0.5.0",
        "pytest>=6.2.5,<7.0",
        "pytest-asyncio>=0.15.1,<0.16",
        "black>=21.9b0,<22.0",
        "isort>=5.9.3,<6.0",
        "mypy>=0.910,<1.0",
        "flake8>=3.9.2,<4.0",
        "tox>=3.24.4,<4.0",
        "coverage>=5.5,<6.0",
        "sphinx>=4.2.0,<5.0",
        "sphinx-rtd-theme>=1.0.0,<2.0",
        "twine>=3.4.2,<4.0",
        "wheel>=0.37.0,<0.38",
        "setuptools>=58.0.0,<59.0",
        "pylint>=2.11.1,<3.0",
        "aiofiles>=0.7.0,<0.8",
        "httpx>=0.19.0,<0.20",
        "typer>=0.4.0,<0.5",
        "rich>=10.12.0,<11.0",
        "pydantic>=1.8.2,<2.0",
        "email-validator>=1.1.3,<2.0",
        "python-multipart>=0.0.5,<0.1",
        "itsdangerous>=2.0.1,<3.0",
        "python-jose[cryptography]>=3.3.0,<4.0",
        "passlib[bcrypt]>=1.7.4,<2.0",
        "SQLAlchemy>=1.4.26,<2.0",
        "alembic>=1.7.4,<2.0",
        "psycopg2-binary>=2.9.1,<3.0",
        "asyncpg>=0.24.0,<0.25",
        "redis>=3.5.3,<4.0",
        "celery>=5.1.2,<6.0",
        "flower>=1.0.0,<2.0",
        "gunicorn>=20.1.0,<21.0",
        "supervisor>=4.2.2,<5.0",
        "pytest-cov>=3.0.0,<4.0",
        "pytest-mock>=3.6.1,<4.0",
        "pytest-xdist>=2.4.0,<3.0",
        "pytest-sugar>=0.9.4,<1.0",
        "pytest-clarity>=1.0.1,<2.0",
    ],
    extras_require={
        "dev": [
            "pre-commit>=2.15.0,<3.0",
            "commitizen>=2.20.0,<3.0",
            "bump2version>=1.0.1,<2.0",
        ],
        "docs": [
            "mkdocs>=1.2.3,<2.0",
            "mkdocs-material>=7.3.6,<8.0",
            "mkdocstrings>=0.16.2,<0.17",
        ],
    },
    entry_points={
        "console_scripts": [
            "salim-api-gen=salim_api_gen.cli:main",
        ],
    },
    package_data={
        "salim_api_gen": ["templates/*.jinja2"],
    },
    include_package_data=True,
)
